version: 2
updates:
- package-ecosystem: maven
  directory: "/."
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.twilio.sdk:twilio
    versions:
    - 8.10.0
    - 8.6.1
    - 8.7.0
    - 8.8.0
    - 8.9.0
  - dependency-name: org.json:json
    versions:
    - "20201115"
  - dependency-name: org.eclipse.jetty:jetty-maven-plugin
    versions:
    - 9.4.26.v20200117
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 9.4.26.v20200117
